project_id = "oopmlreysjzuxzylyheb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[functions.export-calendar]
verify_jwt = false

[functions.calendar-feed]
verify_jwt = false

[functions.sync-google-calendar]
verify_jwt = true

[functions.send-event-notifications]
verify_jwt = true

[functions.generate-event-description]
verify_jwt = true

[storage]
enabled = true
port = 54326
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54327
site_url = "https://gleeworld.org"
additional_redirect_urls = ["https://localhost:3000", "http://127.0.0.1:3000", "https://gleeworld.org"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false
enable_recovery = true
enable_email_change_confirmations = true
enable_phone_change_confirmations = true
leaked_password_protection = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
otp_exp = 86400

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"
otp_exp = 600

[edge_runtime]
enabled = true
port = 54328
inspector_port = 8083

[functions.glee-sheets-api]
verify_jwt = false

[functions.update-scholarships]
verify_jwt = false

[functions.square-oauth]
verify_jwt = true

[functions.create-stripe-checkout]
verify_jwt = false

[functions.verify-stripe-payment]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.google-docs-manager]
verify_jwt = false

[functions.google-places-lookup]
verify_jwt = false

[functions.convert-heic-to-jpeg]
verify_jwt = false

[functions.send-general-inquiry]
verify_jwt = false

[functions.receive-sms-notifications]
verify_jwt = false

[functions.shopping-planner]
verify_jwt = true

[functions.analyze-audio]
verify_jwt = false

[functions.generate-musicxml]
verify_jwt = true

[functions.test-openai]
verify_jwt = true

[functions.radio-proxy]
verify_jwt = false

[functions.azuracast-webhook]
verify_jwt = false

[functions.gw-send-email]
verify_jwt = false
