project_id = "oopmlreysjzuxzylyheb"

[functions.admin-reset-password]
verify_jwt = true

[functions.admin-sign-contract]
verify_jwt = true

[functions.artist-sign-contract]
verify_jwt = false

[functions.auto-enroll-user]
verify_jwt = true

[functions.bulk-w9-email]
verify_jwt = true

[functions.complete-contract-signing]
verify_jwt = false

[functions.generate-combined-pdf]
verify_jwt = true

[functions.gw-generate-sso-token]
verify_jwt = true

[functions.gw-send-email]
verify_jwt = true

[functions.gw-send-sms]
verify_jwt = true

[functions.gw-validate-sso-token]
verify_jwt = false

[functions.handle-sms-approval]
verify_jwt = false

[functions.import-users]
verify_jwt = true

[functions.send-contract-email]
verify_jwt = true

[functions.send-payment-notification]
verify_jwt = true

[functions.send-w9-request]
verify_jwt = true

[functions.w9-ocr-extract]
verify_jwt = true